### ISSUE TITLE
No module named 'FALCON_formatter'

### ISSUE THREAD

**Issue by olechnwin** [zyndagj/FALCON-formatter#2]
I just installed FALCON-formatter using the setuptools but got the following error:

```
bin/FALCON-formatter -h
Traceback (most recent call last):
  File "bin/FALCON-formatter", line 3, in <module>
    from FALCON_formatter import main
ModuleNotFoundError: No module named 'FALCON_formatter'
```

Can someone please help me fix this error? I'm using python 2.7
TIA.

**Comment by zyndagj** [comment]
Are you sure the python module was installed? The `FALCON-formatter` bin should have been installed to a local directory like `$HOME/.local/user/bin` as well.

**Comment by olechnwin** [comment]
@zyndagj Thanks for your reply. I'm not familiar with python so I may not be doing it correctly.
After running the installation, a FALCON-formatter folder is created. These are the files inside the folder:
```
[cx00@qmaster01 FALCON-formatter]$ ls
agave_app  build  FALCON_formatter           LICENSE    setup.py
bin        dist   FALCON_formatter.egg-info  README.md  test_data
```
The program FALCON-formatter is inside bin. So, what I tried to do is `bin/FALCON-formatter -h` from the FALCON-formatter directory
I don't see any FALCON-formatter installed in $HOME/.local/bin

**Comment by zyndagj** [comment]
Yup, it looks like you may not have installed it.

Can you try following:
1. https://github.com/zyndagj/FALCON-formatter#installation
2. https://github.com/zyndagj/FALCON-formatter#cli-usage

and let me know which of those steps could be improved for increased understanding?

**Comment by olechnwin** [comment]
Thanks for your quick response. 
I thought that's what I did. Anyway, I re-installed it and it worked this time. Thank you so much!
The fasta files was generated using Pacbio's sequel. I noticed you created this program back in 2016. Do you happen to know whether I still need to run FALCON-formatter now?

**Comment by zyndagj** [comment]
Awesome!

It may not be necessary with the current version of the tool. I developed this before FALCON was officially apart of the SMRT suite, so they may have improved their input digestion.

If it is still necessary, the workflow will fail during the DAZZ_DB step.
